points_dict = {
    "single": 3,
    "double": 5,
    "triple": 8,
    "home_run": 10,
    "walk": 2,
    "hit_by_pitch": 2,
}

at_bat_list = [
    "field_out",
    "strikeout",
    "single",
    "double",
    "home_run",
    "force_out",
    "grounded_into_double_play",
    "field_error",
    "triple",
    "fielders_choice",
    "double_play",
    "fielders_choice_out",
    "strikeout_double_play",
    "catcher_interf",
    "sac_fly_double_play",
    "triple_play",
]

plate_appearance_list = [
    "field_out",
    "strikeout",
    "single",
    "walk",
    "double",
    "homerun",
    "force_out",
    "grounded_into_double_play",
    "hit_by_pitch",
    "sac_fly",
    "field_error",
    "triple",
    "intent_walk",
    "sac_bunt",
    "fielders_choice",
    "double_play",
    "fielders_choice_out",
    "strikeout_double_play",
    "catcher_interf",
    "sac_fly_double_play",
    "triple_play",
]
